### ISSUE TITLE
Why is Either not a Monad?

### ISSUE THREAD

**Issue by gregberns** [janestreet/base#111]
I'm new to OCaml, but have worked with Rust, Haskell, etc, and was very surprised when I was trying to implement `bind` on `Either`, and it doesn't appear that any of the general implementations have `bind` implemented.

* `Base` is [missing it](https://ocaml.janestreet.com/ocaml-core/latest/doc/base/Base/Either/index.html)
* What I assume is the standard library is [missing it](https://ocaml.org/api/Either.html)

`bind` was the first function I reached for... even before `match`, and the implementation seems quite easy:

```
let bind_either (m: ('e, 'a) Either.t) (f: 'a -> ('e, 'b) Either.t): ('e, 'b) Either.t =
  match m with
  | Right r -> f r
  | Left l -> Left l
```

Am I missing something?

I opened a stackoverflow question about this too: https://stackoverflow.com/questions/67691816/ocaml-why-is-either-not-a-monad

**Comment by bcc32** [comment]
It looks like somebody just answered your question on StackOverflow, but in any case: Base does actually implement the monad operations on Either, but you need to select which type argument the monad operations "operate" over using the submodules `Either.First` or `Either.Second`.  Most likely, you actually want to use `Result`, because it has more features for the kind of error handling done with Either in Haskell, and the names of the variant constructors are much clearer.

**Comment by gregberns** [comment]
Thanks!
