### ISSUE TITLE
Request: Base.List.take_last (or last_n)

### ISSUE THREAD

**Issue by mroch** [janestreet/base#117]
I'm looking for a function that returns the last `n` items of a `List`. I could do `rev (take (rev xs) n)` but that does 2 unnecessary `rev`s.

if there was a `rev_take` that just didn't do this `rev`
https://github.com/janestreet/base/blob/8ea6adb415ebc27fec97e1ae34b9a3d5483eb3f0/src/list.ml#L1078

then we could have

```
let take t_orig n = rev (rev_take t_orig n)
let take_last t_orig n = rev_take (rev t_orig) n
```

**Comment by bcc32** [comment]
I think you will probably be better served by just calling `List.drop` with the appropriate number of elements, since `drop` does not need to allocate any memory at all.  In order to implement take_last you'd need to scan to the end of the list anyway (O(n)), so doing something like:

```ocaml
let take_last list n = List.drop list (List.length list - n)
```

should be as performant or better than rev-then-rev_take.

**Comment by bcc32** [comment]
Closing this issue because I think `List.drop` answers your question, but feel free to reopen if you disagree.

**Comment by aalekseyev** [comment]
This implementation seems to be slightly faster in my very crude measurement (measured ~1.5 faster at taking last 100 elements from a 100000-long list):

```
let rec drop_length ~of_:a b = 
  match (a, b) with
  | ([], b) -> b
  | (_ :: a, []) -> []
  | (_ :: a, _ :: b) -> drop_length ~of_:a b
;;

let rec take_last_v2 list n = 
  drop_length ~of_:(List.drop list n) list;;
```

I'm, not sure where the saving comes from though, as we're making all the same operations. Maybe the gain comes from better locality.

(sorry, got nerd sniped there, the difference doesn't really matter because comparing to "double rev" version both of these versions are ~10x faster)
