### ISSUE TITLE
Error comparing characters

### ISSUE THREAD

**Issue by daniel-larraz** [janestreet/base#95]
This is what I get using OCaml 4.10.0, Base v0.13.2, and Core v0.13.0:
```
utop # 'a' = 'b';;
Line 1, characters 0-3:
Error: This expression has type char but an expression was expected of type int
```
And this using OCaml 4.10.0 and the standard library:
```
utop # 'a' = 'b';;
- : bool = false
```

**Comment by bcc32** [comment]
This is an intentional behavior of Base---when it is opened, the polymorphic comparison operators are shadowed by int-specific comparison operators (see [the readme](https://github.com/janestreet/base#comparison-operators)).

For some background on polymorphic compare and why Base does not export it by default, see [this blog post](https://blog.janestreet.com/the-perils-of-polymorphic-compare/).
